[feat] OAuth 로그인 구현
Minzino/spectrum pull request #27
Opened 2023-03-13 09:23 UTC by Minzino

### ❗️ 이슈 번호

Closes #25 

### 📝 구현 내용
- OAuth 로그인에 대해 공부를 해보느라 구현에 오래걸렸습니다ㅠ
- 로그인은 테스트 코드는 작성하지 못했고 테스트 페이지를 만들어 결과를 확인했습니다.
- 처음에는 다른 사람의 코드를 참고하여 카카오 로그인을 연습으로 구현했었습니다.
- 그 후로 다른 프로바이더들도 궁금해서 구현하게 되었습니다. 
- application-auth.yml에서 각 프로바이더에 대한 OAuthPropeties를 받을 때, OAuthProviderConverter로 각 프로바이더에 맞게 property를 분해 후 InMemoryProviderRepository 클래스를 만들어 각각의 프로바이더에 맞게 저장하도록 하였습니다.

### 💡 결과 & 참고 자료 
- [참고 자료 링크](https://velog.io/@max9106/OAuth4)
- 테스트용 웹페이지로 로그인 테스트
![image](https://user-images.githubusercontent.com/86910955/224654744-f518fbb2-e0de-4bdb-a6e3-540b61dd6e9b.png)

2023-03-13 14:56 UTC, jeremy0405 approved these changes

2023-03-13 14:56 UTC, jeremy0405 commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +    };
OAuth 마다 제공하는 API가 달라서 현재와 같이 하드코딩이 된 것 같은데요. 더 개선할 방법은 없을까요?

2023-03-13 15:01 UTC, ku-kim requested changes
로그인 구현이 처음이었을텐데 고생 넘 많았습니다. @Minzino 
secret 부분 체크했으면 좋겠네요. 
문제가 있다면 기록에 남으니 해당 사항 업데이트하고 push force로 지우는게 좋겠어요. 
일단 Request changes 할게요. 문제 없다면 Approve로 바꾸겠습니닷.!

2023-03-13 15:38 UTC, Minzino commented on src/main/resources/application-auth.yml
> +    expire-length: 1800000
애플리케이션 새로 만들고 수정해놓으려고 합니다!

2023-03-13 16:05 UTC, donggi-lee-bit reviewed
OAuth 로그인 구현이 처음이라고 하셨는데 `provider` 까지 구현하고, 여러 개의 OAuth 로그인을 구현하셨네요! (제 기준) 코드가 깔끔하고 일관성 있게 잘 작성하고 계시는 것 같습니다 👍
제리, 쿠킴이 리뷰를 잘 해주어서 저는 코드 잘 보고갑니다 ㅎㅎㅋㅋㅋ 수고하셨습니다!

2023-03-13 16:05 UTC, donggi-lee-bit commented on src/main/java/com/spectrum/auth/provider/JwtProvider.java
> +    }
리프레쉬 토큰을 만들 때 `payload` 를 파라미터로 받지 않고 메서드 내부에서 랜덤한 숫자를 이용해서 만든 이유가 궁금합니다!
액세스 토큰과는 달리 리프레쉬 토큰에서는 `payload` 를 까서 사용자 정보를 확인할 일이 없어서일까요?? 🤔

2023-03-15 09:44 UTC, ku-kim approved these changes
이미 올라간 key를 완전삭제하는게 좋아보이지만, 테스트용 secret key라면 이전 서비스들 제거하고 다시 만들면 되겠네요~

고생하셨습니다. (actions 깨지는건 쏴리요)

---
+a) 이미 commit된 데이터 완전삭제하는 방법은 아래 링크가 있네요! (저도 첨 봤어요 ㅎㅎ)
https://docs.github.com/ko/github-ae@latest/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

2023-03-15 16:25 UTC, rxdcxdrnine reviewed
고생하셨습니다!
인가와 인증 쪽은 공부한지도 오래되서 코드 리뷰의 퀄리티가 떨어지는 점 감안해주세요 🙇‍♂️

2023-03-15 16:25 UTC, rxdcxdrnine commented on src/main/java/com/spectrum/auth/service/OAuthService.java
> +            .map(entity -> entity.update(
함수에 람다를 활용해 작성되었지만, 이 함수는 함수형 프로그래밍의 관점으로 작성되었다고 볼 수 있을까요? 불변 객체와 암묵적 입출력에 대해 생각해보시면 좋을 것 같습니다.

2023-03-15 16:25 UTC, rxdcxdrnine commented on src/main/java/com/spectrum/auth/service/OAuthService.java
> +        return WebClient.create()
WebClient 를 사용하셨는데 이유가 있나요? WebClient 를 사용하기 위해 webflux 와 관련된 디펜던시가 추가되어야 하는데 굳이 비동기/리액티브 프로그래밍 없이 WebClient 를 사용할 이유를 찾기 어려운 것 같습니다.
(RestTemplate 이 지원 종료 혹은 deprecated 될 예정이어서 그런 것이라면, 실제로는 그런 사실이 없다고 하네요! https://www.youtube.com/watch?v=S4W3cJOuLrU)

2023-03-15 16:25 UTC, rxdcxdrnine commented on .github/workflows/cd-pipeline.yml
> +            sudo docker ps -a -q --filter "name=${{ secrets.IMAGE_NAME }}" | grep -q . && sudo docker stop ${{ secrets.IMAGE_NAME }} && sudo docker rm ${{ secrets.IMAGE_NAME }} | true
배포를 새로할 떄마다 컨테이너를 중지하고 종료한 뒤에 새로 실행하게 되네요. 인스턴스가 중단되었다가 다시 실행되면 문제가 있지 않을까요? 무중단을 위해 위한 배포 전략에는 어떤 것이 있는지 보시면 좋을 것 같습니다. (blue-green, canary, roll-out 등)

2023-03-15 16:25 UTC, rxdcxdrnine commented on .github/workflows/cd-pipeline.yml
> +            sudo docker logs ${{ secrets.IMAGE_NAME }} >> ${{ secrets.IMAGE_NAME }}_log.txt
로그를 파일로 남기면 디스크가 가득차거나 파일을 덮어씌우게될 때 기존의 로그가 삭제되지 않을까요? 로그를 수집하고 로그를 기반으로 관리하려면 어떤 방법이 있을지 알아보시면 좋을 것 같습니다. (elasticsearch, logstash, filebeat 등 elk 스택 위주로)

로그를 보는 것만으로 애플리케이션의 상태를 확인하기에 충분할까요? 로그 외에 메트릭, 트레이스 등 3 caterpillar of observability 에 대해서 알아봅시다. 스프링에서 pull 방식의 메트릭 수집을 위한 메트릭 노출은 로그 푸시보다 훨씬 쉽습니다.

2023-03-15 16:25 UTC, rxdcxdrnine commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +        public UserProfile of(Map<String, Object> attributes) {
기본 자료형 map 보다 id, email, name, imageUrl 을 프로퍼티로 갖는 DTO 클래스를 만들고 해당 클래스를 넘기는게 더 좋지 않을까요? 지금 이 함수는 파라미터 Map<String, Object> 를 받아 계약으로서의 코드를 위반하기 쉽고, 런타임에 예외가 터질 수 있는 부분이 너무 많은 것 같습니다.

2023-03-16 04:35 UTC, Minzino commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +    }
제가 작성한 코드는 provider.providerName으로 enum providerName속성에 접근하여 값을 비교하는데
수정된 코드는 provider에서 providerName을 받아 매개변수로 들어온 providerName을 비교하게되네요!
불필요한 객체 접근을 줄이고 매개변수로 전달받은 값을 직접 사용하니까 더 선호되는 것 같습니다.

2023-03-16 04:36 UTC, Minzino commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +    };
중복되는 값을 ENUM으로 관리하면 될 것 같습니다. 다음 PR 때 한번 리팩토링 해보겠습니다👍

2023-03-16 04:43 UTC, jeremy0405 commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +    }
매개변수로 받은 providerName 은 null 일수도 있지만, provider.providerName 은 OAuthAttributes enum이 관리하는 내부값으로 null 이 아니도록 관리될 것 같아요. 외부에 제공하는 api (method) 인데 외부의 값(null, 'string')에 의해 NullPointerException 이 발생하는 건 좋지 않으니까요.

equals() 메서드는 앞의 비교대상이 null 이 아닌 경우로 세팅하는게 좋습니다.

2023-03-16 04:43 UTC, Minzino commented on src/main/java/com/spectrum/auth/service/OAuthService.java
> +
제가 그 부분을 놓쳤네요! 반영했습니다.

2023-03-16 04:46 UTC, Minzino commented on src/main/java/com/spectrum/auth/service/OAuthService.java
> +        // TODO access token 가져오기
아 그 부분을 계속 간과하네요 왜 필요한지에 대해 적는 연습을 해보겠습니다!

2023-03-16 04:49 UTC, Minzino commented on .github/workflows/cd-pipeline.yml
> +            sudo docker ps -a -q --filter "name=${{ secrets.IMAGE_NAME }}" | grep -q . && sudo docker stop ${{ secrets.IMAGE_NAME }} && sudo docker rm ${{ secrets.IMAGE_NAME }} | true
아직은 테스트 용도로 만들어서 무중단은 적용하지 않았는데 최종으로는 블루-그린배포를 사용할 것 같습니다.

2023-03-16 04:50 UTC, Minzino commented on .github/workflows/cd-pipeline.yml
> +            sudo docker logs ${{ secrets.IMAGE_NAME }} >> ${{ secrets.IMAGE_NAME }}_log.txt
오 이 부분은 고민해보고있었는데 한번 찾아보겠습니다.

2023-03-16 04:51 UTC, Minzino commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +        public UserProfile of(Map<String, Object> attributes) {
Object로 받으며 고민이 많았는데 그 부분도 고려해보겠습니다!

2023-03-16 04:53 UTC, Minzino commented on src/main/java/com/spectrum/auth/service/OAuthService.java
> +        return WebClient.create()
이것도 한번 고쳐보고 이유를 적어보겠습니다! 리뷰 감사합니다.

2023-03-16 04:55 UTC, Minzino commented on src/main/java/com/spectrum/auth/OAuthAttributes.java
> +    }
오...null이 문제였구나 리뷰 감사합니다

2023-03-16 05:43 UTC, Minzino commented on build.gradle
> +
1. Jib를 사용하면 이미지를 Docker Hub, ECS 같은 registry에 직접 푸시할 수 있고, Dockerfile을 작성하고 Docker 데몬을 실행하지 않아도 되는 점이 편해보여서 사용하게 되었습니다.
2. 여러 이미지가 많아서 친숙한 amazon 이미지를 사용해봤는데 이미지 별로 크기의 차이가 있는 줄 몰랐습니다. 담부터는 한번 알아보고 사용해야겠네요.
3. 알아보니까 latest 태그는 항상 가장 최신 버전을 가리키기때문에 버전관리에 어려움이 있다. 
3-1. latest 태그는 보안 취약점을 가질 수 있는데 이유는 새로운 버전으로 업데이트하지 않고 사용되고 있는 경우에는 특히 위험하다고 하는군요.

2023-03-16 06:35 UTC, Minzino commented on src/main/java/com/spectrum/auth/dto/LoginResponse.java
> +    @Builder
리뷰 감사합니다! 필드값에 validation을 사용하여 필수값에는 notnull을 사용하면 될 것 같습니다.

2023-03-16 15:17 UTC, merged