[loadtest] 부하테스트 및 게시글 조회 성능 개선
Minzino/spectrum pull request #40
Opened 2023-04-14 12:46 UTC by Minzino

### ❗️ 이슈 번호

Closes #37 
Closes #39 

<br>

### 📝 구현 내용

ngrinder로 조회 기능에 대해 부하테스트를 해보았습니다.
아무래도 전체 조회를 구현했다보니 성능이 엄청 저조한 것을 확인 할 수 있었습니다;;
성능 개선을 진행하며 문서를 작성했고 조회는 페이징, 인덱싱을 적용하였고 
CUD 성능 개선은 default_batch_fetch_size를 사용했는데 
이것때문에 조회 성능이 더 나빠져서 다시 빼버렸습니다..

총 성능 개선은 

1. 페이징 처리 전과 후의 성능 차이
- 3.2 -> 191.5 , 평균 TPS가 약 (191.5 / 2.2 - 1) * 100% = 8,609% 증가했습니다.
2. 페이징 처리 후와 인덱싱 적용 후의 성능 차이
- 191.5 -> 588.9 , 평균 TPS가 약 (588.9 / 191.5 - 1) * 100% = 207% 증가했습니다.
3. 인덱싱 적용 후와 커넥션 풀 증가 후의 성능 차이
- 588.9 -> 636.9 , 평균 TPS가 약 (636.9 / 588.9 - 1) * 100% = 8% 증가했습니다.

다음에는 직접 aws에 배포해서 모니터링 툴과 고가용성으로 인프라를 구축해서 성능 테스트를 해보겠습니다!

[Read 성능 개선기](https://meenzino.notion.site/Read-c3a8b9bb7c914edaa09c0f9105e4a844)
[CUD(create,update,delete) 성능 개선기](https://meenzino.notion.site/CUD-create-update-delete-86ab30bb76694646946235a1e82038df)
<br>

### 💡 결과

- 성능 개선 전
![](https://meenzino.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F8c2015d5-8049-4166-82b6-ec2272378740%2FUntitled.png?id=3f0d43c1-5ac5-4611-aa76-0c0eb4443562&table=block&spaceId=9d32437f-ad77-480c-94b0-229d3642279b&width=360&userId=&cache=v2)

- 1차 개선 페이징 처리 후
![](https://meenzino.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F06b135f7-93ef-46dc-94c1-64ac08cc098f%2FUntitled.png?id=a425e505-1c99-4186-8258-5a760bde58bd&table=block&spaceId=9d32437f-ad77-480c-94b0-229d3642279b&width=360&userId=&cache=v2)

- 2차 개선 인덱싱 적용 후
![](https://meenzino.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F8df91629-3f7e-4f35-8514-846a00e24dd2%2FUntitled.png?id=fad1f0db-000f-4275-bbaa-369314e67b74&table=block&spaceId=9d32437f-ad77-480c-94b0-229d3642279b&width=360&userId=&cache=v2)

- 3차 개선 DB 커넥션 풀 증가 시킨 후
![](https://meenzino.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F1160e6af-d18f-40aa-bf6d-a5420f80dba3%2FUntitled.png?id=2345f19a-c3ac-43a3-b0c2-fb9d1c26c318&table=block&spaceId=9d32437f-ad77-480c-94b0-229d3642279b&width=360&userId=&cache=v2)

### 참고자료

- [https://github.com/naver/ngrinder/wiki/Installation-Guide](https://github.com/naver/ngrinder/wiki/Installation-Guide)
- [https://leezzangmin.tistory.com/42](https://leezzangmin.tistory.com/42)
- [https://velog.io/@cmsskkk/NGrinder-Redis-Caching](https://velog.io/@cmsskkk/NGrinder-Redis-Caching)
- [http://ngrinder.373.s1.nabble.com/process-thread-td2636.html](http://ngrinder.373.s1.nabble.com/process-thread-td2636.html)
- [https://velog.io/@hellonayeon/nGrinder-install-and-how-to-use-memo](https://velog.io/@hellonayeon/nGrinder-install-and-how-to-use-memo)

2023-04-14 15:17 UTC, donggi-lee-bit reviewed
성능 개선을 잘하셨네요 👍
지금 성능 개선에서 헤매고 있던터라 좋은 인사이트를 얻고 갑니다!!!

볼 때마다 느끼는 거지만 코드를 깔끔하게 잘 짜네요 👍

2023-04-14 15:17 UTC, donggi-lee-bit commented on script/ngrinder/withlogin.groovy
> +    }
`accessToken` 을 가져오는 작업을 스레드가 준비될 때(?) 하는군요!
`beforeThread()` 에서 하는 것은 의도된 것인가요??

로그인 정보가 필요한 CUD 테스트할 때 로그인 처리를 이렇게 하면 되는구나 하나 알아갑니다!

2023-04-14 15:17 UTC, donggi-lee-bit commented on script/ngrinder/withlogin.groovy
> +        HTTPResponse response = request.POST("http://127.0.0.1:8080/api/posts", jsonData)
`body` 데이터를 최종적으로 `byte[]` 타입으로 넘겨주는데, 생성 순서가 그렇다면
- `JsonBuilder()` 메서드로 넘겨줄 `json` 데이터 입력
- `toString()` 메서드로 `jsonBody` 라는 변수에 `String` 타입으로 저장하고
- 최종적으로 `getBytes()` 로 `byte[]` 타입으로 넘겨주게 되는 순서가 맞을까요?

2023-04-14 15:17 UTC, donggi-lee-bit commented on sql/dummy_data.sql
`sql` 로 더미 데이터를 넣어주셨군요! 👏

2023-04-14 15:17 UTC, donggi-lee-bit commented on src/main/java/com/spectrum/domain/post/Post.java
> +@Table(name = "posts", indexes = {@Index(name = "idx_title", columnList = "title")})
`Index` 를 걸어주셨군요! 어떻게 `Index`가 걸리는지 같이 학습해보아요 😆 ㅋㅋㅋㅋ

2023-04-14 15:17 UTC, donggi-lee-bit commented on src/test/java/com/spectrum/service/post/PostServiceTest.java
`Pagination` 을 추가하고 테스트도 챙기셨군요 👍
페이징 처리로 `API` 에 변경사항이 생겼을 것 같은데 `Controller` 테스트도 리팩토링 해주어야겠네요??!

2023-04-15 12:30 UTC, ku-kim requested changes

2023-04-15 12:30 UTC, ku-kim commented on src/main/java/com/spectrum/controller/post/PostController.java
>          return ResponseEntity.ok().body(postListResponse);
p1;

- int page, int size에 방어로직 추가가 필요해보여요!
- 페이징 로직인데 response에 page 위치나 남은 size 정보가 없네요. 이렇게 되면 클라쪽에서 페이징을 사용하지 못할 거 같아요. Page 객체로 응답 해주거나 별도의 필드를 추가해줘야 할 거 같습니다.

2023-04-15 12:30 UTC, ku-kim commented on src/main/java/com/spectrum/domain/post/Post.java
> +@Table(name = "posts", indexes = {@Index(name = "idx_title", columnList = "title")})
p1; 인덱스를 걸어 성능이 증가했다고했는데 어떻게 증가하게 된거에요?
부하테스트가 전체 조회만있는게 아닌가요?

2023-04-15 12:30 UTC, ku-kim commented on script/ngrinder/view_post.groovy
> +@RunWith(GrinderRunner)
p3; 불필요한 주석이 있어요.

2023-04-20 14:09 UTC, Minzino commented on script/ngrinder/view_post.groovy
> +@RunWith(GrinderRunner)
주석이 있는지 확인을 못했네요ㅠㅠ수정했습니다!

2023-04-20 14:11 UTC, Minzino commented on src/main/java/com/spectrum/controller/post/PostController.java
>          return ResponseEntity.ok().body(postListResponse);
페이징 처리만 생각하다보니까 놓친게 많네요;;
page번호와 size에 방어로직을 추가하였고, response에 현재 페이지의 정보를 넣어주었습니다!

2023-04-20 16:06 UTC, Minzino commented on src/main/java/com/spectrum/domain/post/Post.java
> +@Table(name = "posts", indexes = {@Index(name = "idx_title", columnList = "title")})
제가 급하게 구현하다 보니 제대로 확인하지 못했습니다;;
지금 생각해보니 인덱스가 필요 없는 것 같네요.. 
title에 인덱스를 걸어주었지만 게시글 검색을 구현해야 성능 증가를 확인할 수 있을 것 같습니다.
다음 구현에 검색 기능을 추가하여 테스트를 진행해보겠습니다.

2023-04-29 16:05 UTC, ku-kim requested changes
커서 추가해주면 좋을거같습니다.!

2023-05-20 04:27 UTC, ku-kim approved these changes
고생 많으셨습니다~

2023-05-20 04:27 UTC, ku-kim commented on src/main/java/com/spectrum/controller/post/dto/PostPageResponse.java
> +        this.lastIdInPage = lastIdInPage;
p3; lastCursor 네이밍은 어떠세요?

2023-05-20 04:27 UTC, ku-kim commented on src/docs/asciidoc/post/post.adoc
> +|`cursor`|마지막 게시글의 번호
p3; cursor 부터 size 크기만큼 달라는 것 아닌가요?

2023-05-20 14:13 UTC, Minzino commented on src/main/java/com/spectrum/controller/post/dto/PostPageResponse.java
> +        this.lastIdInPage = lastIdInPage;
리뷰 감사합니다!
cursor로 변경하고 response 값은 신경쓰지 못했네요;;
수정했습니다ㅎㅎ

2023-05-20 14:13 UTC, Minzino commented on src/docs/asciidoc/post/post.adoc
> +|`cursor`|마지막 게시글의 번호
넵 좀 더 명확한 설명이 좋겠네요!
수정했습니다ㅎㅎ

2023-05-20 14:13 UTC, merged